--Total Customers by Countries
SELECT country, COUNT(DISTINCT customer_id) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;

--Total Customers by Gender
SELECT gender, COUNT(DISTINCT customer_id) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;

--Total Products by Category
SELECT category, COUNT(product_id) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;

--Average Costs in each Category
SELECT category, AVG(cost) AS avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC;

--Total Revenue Generated for each Category
SELECT DISTINCT p.category, SUM(f.sales_amount) AS total_revenue
FROM gold.dim_products AS p
LEFT JOIN gold.fact_sales AS f
ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;

--Total revenue generated by each customer
SELECT DISTINCT customer_key, SUM(sales_amount) AS total_sales
FROM gold.fact_sales
GROUP BY customer_key
ORDER BY total_sales DESC;

--Distribution of sold items across countries
SELECT c.country, SUM(f.quantity) AS total_quantities
FROM gold.dim_customers AS c
LEFT JOIN gold.fact_sales AS f
ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_quantities DESC;